language: php

php:
    - 5.4
    - 5.5
    - 5.6
    - hhvm

before_script:
    - travis_retry composer install --no-interaction --dev

script: vendor/bin/phpunit --verbose

matrix:
    allow_failures:
        -php: hhvm
    fast_finish: true